### ISSUE TITLE
Project EOL sometime soon. No definite date

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4MapperTest#28]
There is pretty much no path forward for this project. I am ending my support for several of my current projects including this one. There will be one small patch release put out there before I decide to close this repository. There is no timetable for when I plan to close this repo other than soon.

**Comment by Trihy** [comment]
Hi ryo, sorry to post here, I found a problem with ds4windows.

Using this proile, buttons get mirrored on my second dualsense. Every macro gets replied on the second controller, just tapping buttons on controller 1, Even if the second controller is using a total diferent proile.

I hold ie. X button for macro on that button on controller 1 and macro gets executed on controller 1 and 2.

<?xml version="1.0" encoding="utf-8"?>



<DS4Windows app_version="3.1.12" config_version="5">
  <touchToggle>True</touchToggle>
  <idleDisconnectTimeout>300</idleDisconnectTimeout>
  <outputDataToDS4>True</outputDataToDS4>
  <Color>17,0,0</Color>
  <RumbleBoost>100</RumbleBoost>
  <RumbleAutostopTime>0</RumbleAutostopTime>
  <LightbarMode>DS4Win</LightbarMode>
  <ledAsBatteryIndicator>False</ledAsBatteryIndicator>
  <FlashType>0</FlashType>
  <flashBatteryAt>0</flashBatteryAt>
  <touchSensitivity>30</touchSensitivity>
  <LowColor>0,0,0</LowColor>
  <ChargingColor>0,0,0</ChargingColor>
  <FlashColor>0,0,0</FlashColor>
  <touchpadJitterCompensation>True</touchpadJitterCompensation>
  <lowerRCOn>False</lowerRCOn>
  <tapSensitivity>80</tapSensitivity>
  <doubleTap>True</doubleTap>
  <scrollSensitivity>2</scrollSensitivity>
  <LeftTriggerMiddle>0</LeftTriggerMiddle>
  <RightTriggerMiddle>0</RightTriggerMiddle>
  <TouchpadInvert>0</TouchpadInvert>
  <TouchpadClickPassthru>False</TouchpadClickPassthru>
  <L2AntiDeadZone>0</L2AntiDeadZone>
  <R2AntiDeadZone>0</R2AntiDeadZone>
  <L2MaxZone>100</L2MaxZone>
  <R2MaxZone>100</R2MaxZone>
  <L2MaxOutput>100</L2MaxOutput>
  <R2MaxOutput>100</R2MaxOutput>
  <ButtonMouseSensitivity>25</ButtonMouseSensitivity>
  <ButtonMouseOffset>0.008</ButtonMouseOffset>
  <Rainbow>0</Rainbow>
  <MaxSatRainbow>100</MaxSatRainbow>
  <LSDeadZone>3</LSDeadZone>
  <RSDeadZone>3</RSDeadZone>
  <LSAntiDeadZone>2</LSAntiDeadZone>
  <RSAntiDeadZone>2</RSAntiDeadZone>
  <LSMaxZone>100</LSMaxZone>
  <RSMaxZone>100</RSMaxZone>
  <LSVerticalScale>100</LSVerticalScale>
  <RSVerticalScale>100</RSVerticalScale>
  <LSMaxOutput>100</LSMaxOutput>
  <RSMaxOutput>100</RSMaxOutput>
  <LSMaxOutputForce>False</LSMaxOutputForce>
  <RSMaxOutputForce>False</RSMaxOutputForce>
  <LSDeadZoneType>Radial</LSDeadZoneType>
  <RSDeadZoneType>Radial</RSDeadZoneType>
  <LSAxialDeadOptions>
    <DeadZoneX>10</DeadZoneX>
    <DeadZoneY>10</DeadZoneY>
    <MaxZoneX>100</MaxZoneX>
    <MaxZoneY>100</MaxZoneY>
    <AntiDeadZoneX>20</AntiDeadZoneX>
    <AntiDeadZoneY>20</AntiDeadZoneY>
    <MaxOutputX>100</MaxOutputX>
    <MaxOutputY>100</MaxOutputY>
  </LSAxialDeadOptions>
  <RSAxialDeadOptions>
    <DeadZoneX>10</DeadZoneX>
    <DeadZoneY>10</DeadZoneY>
    <MaxZoneX>100</MaxZoneX>
    <MaxZoneY>100</MaxZoneY>
    <AntiDeadZoneX>20</AntiDeadZoneX>
    <AntiDeadZoneY>20</AntiDeadZoneY>
    <MaxOutputX>100</MaxOutputX>
    <MaxOutputY>100</MaxOutputY>
  </RSAxialDeadOptions>
  <LSRotation>0</LSRotation>
  <RSRotation>0</RSRotation>
  <LSFuzz>0</LSFuzz>
  <RSFuzz>0</RSFuzz>
  <LSOuterBindDead>75</LSOuterBindDead>
  <RSOuterBindDead>75</RSOuterBindDead>
  <LSOuterBindInvert>False</LSOuterBindInvert>
  <RSOuterBindInvert>False</RSOuterBindInvert>
  <LSDeltaAccelSettings>
    <Enabled>False</Enabled>
    <Multiplier>4</Multiplier>
    <MaxTravel>0.2</MaxTravel>
    <MinTravel>0.01</MinTravel>
    <EasingDuration>0.2</EasingDuration>
    <MinFactor>1</MinFactor>
  </LSDeltaAccelSettings>
  <RSDeltaAccelSettings>
    <Enabled>False</Enabled>
    <Multiplier>4</Multiplier>
    <MaxTravel>0.2</MaxTravel>
    <MinTravel>0.01</MinTravel>
    <EasingDuration>0.2</EasingDuration>
    <MinFactor>1</MinFactor>
  </RSDeltaAccelSettings>
  <SXDeadZone>0.25</SXDeadZone>
  <SZDeadZone>0.25</SZDeadZone>
  <SXMaxZone>100</SXMaxZone>
  <SZMaxZone>100</SZMaxZone>
  <SXAntiDeadZone>0</SXAntiDeadZone>
  <SZAntiDeadZone>0</SZAntiDeadZone>
  <Sensitivity>1|1|1|1|1|1</Sensitivity>
  <ChargingType>0</ChargingType>
  <MouseAcceleration>False</MouseAcceleration>
  <ButtonMouseVerticalScale>100</ButtonMouseVerticalScale>
  <LaunchProgram>
  </LaunchProgram>
  <DinputOnly>False</DinputOnly>
  <StartTouchpadOff>False</StartTouchpadOff>
  <TouchpadOutputMode>Mouse</TouchpadOutputMode>
  <SATriggers>-1</SATriggers>
  <SATriggerCond>and</SATriggerCond>
  <SASteeringWheelEmulationAxis>None</SASteeringWheelEmulationAxis>
  <SASteeringWheelEmulationRange>360</SASteeringWheelEmulationRange>
  <SASteeringWheelFuzz>0</SASteeringWheelFuzz>
  <SASteeringWheelSmoothingOptions>
    <SASteeringWheelUseSmoothing>False</SASteeringWheelUseSmoothing>
    <SASteeringWheelSmoothMinCutoff>0.1</SASteeringWheelSmoothMinCutoff>
    <SASteeringWheelSmoothBeta>0.1</SASteeringWheelSmoothBeta>
  </SASteeringWheelSmoothingOptions>
  <TouchDisInvTriggers>-1</TouchDisInvTriggers>
  <GyroSensitivity>100</GyroSensitivity>
  <GyroSensVerticalScale>100</GyroSensVerticalScale>
  <GyroInvert>0</GyroInvert>
  <GyroTriggerTurns>True</GyroTriggerTurns>
  <GyroControlsSettings>
    <Triggers>-1</Triggers>
    <TriggerCond>and</TriggerCond>
    <TriggerTurns>True</TriggerTurns>
    <Toggle>False</Toggle>
  </GyroControlsSettings>
  <GyroMouseSmoothingSettings>
    <UseSmoothing>False</UseSmoothing>
    <SmoothingMethod>none</SmoothingMethod>
    <SmoothingWeight>50</SmoothingWeight>
    <SmoothingMinCutoff>1</SmoothingMinCutoff>
    <SmoothingBeta>0.7</SmoothingBeta>
  </GyroMouseSmoothingSettings>
  <GyroMouseHAxis>0</GyroMouseHAxis>
  <GyroMouseDeadZone>10</GyroMouseDeadZone>
  <GyroMouseMinThreshold>1</GyroMouseMinThreshold>
  <GyroMouseToggle>False</GyroMouseToggle>
  <GyroOutputMode>Controls</GyroOutputMode>
  <GyroMouseStickTriggers>-1</GyroMouseStickTriggers>
  <GyroMouseStickTriggerCond>and</GyroMouseStickTriggerCond>
  <GyroMouseStickTriggerTurns>True</GyroMouseStickTriggerTurns>
  <GyroMouseStickHAxis>0</GyroMouseStickHAxis>
  <GyroMouseStickDeadZone>30</GyroMouseStickDeadZone>
  <GyroMouseStickMaxZone>830</GyroMouseStickMaxZone>
  <GyroMouseStickOutputStick>RightStick</GyroMouseStickOutputStick>
  <GyroMouseStickOutputStickAxes>XY</GyroMouseStickOutputStickAxes>
  <GyroMouseStickAntiDeadX>0.4</GyroMouseStickAntiDeadX>
  <GyroMouseStickAntiDeadY>0.4</GyroMouseStickAntiDeadY>
  <GyroMouseStickInvert>0</GyroMouseStickInvert>
  <GyroMouseStickToggle>False</GyroMouseStickToggle>
  <GyroMouseStickMaxOutput>100</GyroMouseStickMaxOutput>
  <GyroMouseStickMaxOutputEnabled>False</GyroMouseStickMaxOutputEnabled>
  <GyroMouseStickVerticalScale>100</GyroMouseStickVerticalScale>
  <GyroMouseStickSmoothingSettings>
    <UseSmoothing>False</UseSmoothing>
    <SmoothingMethod>none</SmoothingMethod>
    <SmoothingWeight>50</SmoothingWeight>
    <SmoothingMinCutoff>0.4</SmoothingMinCutoff>
    <SmoothingBeta>0.7</SmoothingBeta>
  </GyroMouseStickSmoothingSettings>
  <GyroSwipeSettings>
    <DeadZoneX>80</DeadZoneX>
    <DeadZoneY>80</DeadZoneY>
    <Triggers>-1</Triggers>
    <TriggerCond>and</TriggerCond>
    <TriggerTurns>True</TriggerTurns>
    <XAxis>Yaw</XAxis>
    <DelayTime>0</DelayTime>
  </GyroSwipeSettings>
  <ProfileActions>Disconnect Controller</ProfileActions>
  <BTPollRate>4</BTPollRate>
  <LSOutputCurveMode>linear</LSOutputCurveMode>
  <LSOutputCurveCustom>
  </LSOutputCurveCustom>
  <RSOutputCurveMode>linear</RSOutputCurveMode>
  <RSOutputCurveCustom>
  </RSOutputCurveCustom>
  <LSSquareStick>False</LSSquareStick>
  <RSSquareStick>False</RSSquareStick>
  <SquareStickRoundness>5</SquareStickRoundness>
  <SquareRStickRoundness>5</SquareRStickRoundness>
  <LSAntiSnapback>False</LSAntiSnapback>
  <RSAntiSnapback>False</RSAntiSnapback>
  <LSAntiSnapbackDelta>135</LSAntiSnapbackDelta>
  <RSAntiSnapbackDelta>135</RSAntiSnapbackDelta>
  <LSAntiSnapbackTimeout>50</LSAntiSnapbackTimeout>
  <RSAntiSnapbackTimeout>50</RSAntiSnapbackTimeout>
  <LSOutputMode>Controls</LSOutputMode>
  <RSOutputMode>Controls</RSOutputMode>
  <LSOutputSettings>
    <FlickStickSettings>
      <RealWorldCalibration>5.3</RealWorldCalibration>
      <FlickThreshold>0.9</FlickThreshold>
      <FlickTime>0.1</FlickTime>
      <MinAngleThreshold>0</MinAngleThreshold>
    </FlickStickSettings>
  </LSOutputSettings>
  <RSOutputSettings>
    <FlickStickSettings>
      <RealWorldCalibration>5.3</RealWorldCalibration>
      <FlickThreshold>0.9</FlickThreshold>
      <FlickTime>0.1</FlickTime>
      <MinAngleThreshold>0</MinAngleThreshold>
    </FlickStickSettings>
  </RSOutputSettings>
  <L2OutputCurveMode>linear</L2OutputCurveMode>
  <L2OutputCurveCustom>
  </L2OutputCurveCustom>
  <L2TwoStageMode>Disabled</L2TwoStageMode>
  <R2TwoStageMode>Disabled</R2TwoStageMode>
  <L2HipFireTime>100</L2HipFireTime>
  <R2HipFireTime>100</R2HipFireTime>
  <L2TriggerEffect>None</L2TriggerEffect>
  <R2TriggerEffect>None</R2TriggerEffect>
  <R2OutputCurveMode>linear</R2OutputCurveMode>
  <R2OutputCurveCustom>
  </R2OutputCurveCustom>
  <SXOutputCurveMode>linear</SXOutputCurveMode>
  <SXOutputCurveCustom>
  </SXOutputCurveCustom>
  <SZOutputCurveMode>linear</SZOutputCurveMode>
  <SZOutputCurveCustom>
  </SZOutputCurveCustom>
  <TrackballMode>False</TrackballMode>
  <TrackballFriction>10</TrackballFriction>
  <TouchRelMouseRotation>0</TouchRelMouseRotation>
  <TouchRelMouseMinThreshold>1</TouchRelMouseMinThreshold>
  <TouchpadAbsMouseSettings>
    <MaxZoneX>90</MaxZoneX>
    <MaxZoneY>90</MaxZoneY>
    <SnapToCenter>False</SnapToCenter>
  </TouchpadAbsMouseSettings>
  <TouchpadMouseStick>
    <DeadZone>0</DeadZone>
    <MaxZone>8</MaxZone>
    <OutputStick>RightStick</OutputStick>
    <OutputStick>XY</OutputStick>
    <AntiDeadX>0.4</AntiDeadX>
    <AntiDeadY>0.4</AntiDeadY>
    <Invert>0</Invert>
    <MaxOutput>100</MaxOutput>
    <MaxOutputEnabled>False</MaxOutputEnabled>
    <VerticalScale>100</VerticalScale>
    <OutputCurve>Linear</OutputCurve>
    <Rotation>0</Rotation>
    <SmoothingSettings>
      <SmoothingMethod>None</SmoothingMethod>
      <SmoothingMinCutoff>0.8</SmoothingMinCutoff>
      <SmoothingBeta>0.7</SmoothingBeta>
    </SmoothingSettings>
  </TouchpadMouseStick>
  <AbsMouseRegionSettings>
    <AbsWidth>1</AbsWidth>
    <AbsHeight>1</AbsHeight>
    <AbsXCenter>0.5</AbsXCenter>
    <AbsYCenter>0.5</AbsYCenter>
    <AntiRadius>0</AntiRadius>
    <SnapToCenter>True</SnapToCenter>
  </AbsMouseRegionSettings>
  <TouchpadButtonMode>Click</TouchpadButtonMode>
  <DualSenseControllerSettings>
    <RumbleSettings>
      <EmulationMode>Accurate</EmulationMode>
      <EnableGenericRumbleRescale>False</EnableGenericRumbleRescale>
      <HapticPowerLevel>0</HapticPowerLevel>
    </RumbleSettings>
  </DualSenseControllerSettings>
  <OutputContDevice>X360</OutputContDevice>
  <Control>
    <Button>
      <TouchLeft>Back</TouchLeft>
      <TouchRight>Start</TouchRight>
      <Mute>Start</Mute>
    </Button>
    <Macro>
      <L1>272/320/272/320</L1>
      <R1>273/320/273/320</R1>
      <Square>263/320/263/320</Square>
      <Triangle>264/320/264/320</Triangle>
      <Circle>262/320/262/320</Circle>
      <Cross>261/320/261/320</Cross>
    </Macro>
    <KeyType>
      <L1>HoldMacro</L1>
      <R1>HoldMacro</R1>
      <Square>HoldMacro</Square>
      <Triangle>HoldMacro</Triangle>
      <Circle>HoldMacro</Circle>
      <Cross>HoldMacro</Cross>
    </KeyType>
  </Control>
  <ShiftControl />
</DS4Windows>

Feel free to delete it if doesnt belong here.

**Comment by Ryochan7** [comment]
Thinking back on it, I believe that is a problem with the macro system itself in DS4Windows. I would have to confirm but I believe the Mapping class only uses one static array to represent any macro output button changes (macroControl); looked at Mapping.cs and that is the case. Therefore, any controller output will apply across all emulated output controllers. Most of the time it would not be a problem as only one controller would be in use.

In theory, it would likely be possible to group the macro data and create multiple instances so that each controller can function differently. I have always considered the macro system in maintenance mode so I barely touched it; I never used the system in any profile I made for a game. It is going to be up to someone else to fix that problem.

This project has no macro system in place and it will likely stay that way. I am trying to wrap up some tasks on various projects before closing them for good as well.

**Comment by Ryochan7** [comment]
I feel like I am close to just ending this project as well.

**Comment by Dont-Know-Nothing** [comment]
Sad to hear but... everything good has to end right?. On the positive side, is pretty much usable in this state (at least for me). Again, thanks for this project, your effort and your time put in this. Maybe some day I could learn WPF + MVVM and try to start where you left? :) 

Thanks!

**Comment by Ryochan7** [comment]
I have reopened this project for the time being. I mainly wanted to backup other changes made to the Git repository before I reinstall Windows. Not sure how much I will tweak.

**Comment by Trihy** [comment]
Good to see this one back. I never found a mapper with turbo buttons. Dont know why. Maybe people doesnt play old games anymore. But I know almost nothing about coding and was really easy to add turbo buttons to tmote.

ie. for button A

private bool turboAActive = false;
private readonly object turboALock = new object();

case "aturbo":
                device.Cont.SetButtonState(Xbox360Button.A, true);
                
                lock (turboALock)
                {
                    if (!turboAActive)
                    {
                        turboAActive = true;
                        Thread turboThread = new Thread(() =>
                        {
                            while (turboAActive)
                            {
                                device.Cont.SetButtonState(Xbox360Button.A, true);
                                Thread.Sleep(30);
                                device.Cont.SetButtonState(Xbox360Button.A, false);
                                Thread.Sleep(30);
                            }
                        });
                        turboThread.Start();
                    }
                }
                break;

Thread Sleep is somehow hated, but also tried with task.delay and had better output with thread sleep. 

Then wanted to add the same for DS4W but was impossible with my knowledge. Just a feature suggestion for this one.

**Comment by Ryochan7** [comment]
There is some rudimentary support for turbo actions in this mapper but it is not exposed in the GUI. I never had a use for it so I did not worry about putting anything in the GUI to change turbo state or timing. I tested the functionality again and it works for simple key and button presses.

https://github.com/Ryochan7/DS4MapperTest/blob/limping_tweaks/DS4MapperTest/ActionUtil/NormalPressFunc.cs#L139

**Comment by Trihy** [comment]
Thanks. I think I can mod that code accordingly. 

Ryo, if you still use wiimotes, check user suegrini fork. He added lot of stuff. Even speaker audio support,

**Comment by Ryochan7** [comment]
I have not played any lightgun games in a while. Getting a 4IR setup for the Wiimote would be pretty useful. I am curious how the points would be interpreted for where the cursor should be positioned when using 4 IR points. I also wonder how close the results could be compared to Gun4IR.

**Comment by Trihy** [comment]
Hi, it's all on his commits. It support 2 IR bars or "diamond" layout. It's based on open source openfire project. 

The 4IR commit is an interesting read. There are many changes there. 

Give it a try when you have some time. Pretty amazing all the stuff he packed there.


Lately we are stuck here https://github.com/Suegrini/Touchmote/commit/3237af0cd211ce4418ae4d29da5342a0812af97f if you want to help with some testing or ideas! 

There is also a wiimotelib fork on his repositories.
